site_name: "Ostorlab."
site_description: "Ostorlab is an open-source project to help automate security testing. Ostorlab standardizes interoperability between tools in a consistent, scalable, and performant way."
site_url: "https://ostorlab.github.io/"
repo_url: "https://github.com/vuejs/vue"
repo_name: "Ostorlab/ostorlab"
nav:
  - Home: README.md
  - Guide: guide/README.md
  - Remediation: remediation/README.md
  - Analysis: ide/README.md
  - Tutorials:
      - tutorials/run-your-first-scan.md
  - API: api/README.md
  - Learn More:
    - FAQ: faq/README.md
    - Product:
        - product/README.md
        - Knowledge Base: changelog/README.md
        - Changelog: changelog/README.md
        - User management: user_management/README.md
    - Miscellaneous:
        - Compliance: compliance/README.md
        - Enterprise: enterprise/README.md
        - Privacy: privacy/README.md
        - Terms: terms/README.md

plugins:
  - search
  - mkdocstrings:
      watch:
        - src/ostorlab

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - md_in_html
theme:
  name: "material"
  logo: "https://www.ostorlab.co/img/logo/logo-emblem.png"
  palette:
    - scheme: ostorlab
  features:
  - navigation.tabs
  - navigation.top
extra_css:
  - stylesheets/extra.css
